import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner';
import styles from '../styles/Home.module.css';

export default function Home() {
  const onBannerBtnClick = () => {
    console.log('banner button');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Me Find Coffee</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText='Find shops near me'
          handleOnClick={onBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src='/static/hero-image.png' alt='' width={600} height={300} />
        </div>
      </main>
    </div>
  );
}
