import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner/banner';
import Card from '../components/card/card';
import styles from '../styles/Home.module.css';
import coffeeShops from '../data/coffee-shops.json';

export default function Home() {
  const onBannerBtnClick = () => {
    console.log('banner button');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Me Find Coffee</title>
        {/* Icon provided by Icons8 https://icons8.com/icon/KRQgTwddkc3A/coffee */}
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText='Find shops near me'
          handleOnClick={onBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src='/static/hero-image.png'
            alt='coffee image'
            width={600}
            height={300}
          />
        </div>
        <div className={styles.cardLayout}>
          {coffeeShops.map((coffeeShop) => {
            return (
              <Card
                name={coffeeShop.name}
                key={coffeeShop.id}
                href={`/coffee-shop/${coffeeShop.id}`}
                imageUrl={coffeeShop.imageUrl}
                className={styles.card}
              />
            );
          })}
        </div>
      </main>
    </div>
  );
}
